name: YD-DailyQuest
main: net.starly.quest.YDDailyQuest
author: Starly Team
website: http://starly.kr/

description: DailyQuest Plugin.

softdepend:
  - ST-Core
  - Citizens

version: 1.0
api-version: 1.19

commands:

  배달:
    description: 배달 명령어